server:
  port: 8660

spring:
  application:
    name: feign

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
logging:
  file: /var/log/feign.log  
    
#protocol:
#  scheme: https
#  port: 6660
#  tomcat:
#    accept-count: 1000
#    max-threads: 1000
#    max-connections: 2000
#  ssl:
#    key-store: F:\httpskey\kserver.p12
#    key-store-password: 123456
#    key-password: 123456
#    keyStoreType: JKS
#    client-auth: true
#    trust-store: F:\httpskey\tserver.keystore
#    trust-store-password: 123456
#    trust-store-type: JKS
